// Persona profile — PLAN.md §4.2. A distilled "who I am" document (values,
// voice, decision heuristics, expertise areas), auto-maintained from the
// vault's strongest notes and injected into every system prompt right after
// Identity Core (persona.js buildSystemPrompt).
//
// The profile IS a note — titled 'Persona Profile' — so the owner can read,
// edit, or delete it exactly like any other note. Regeneration overwrites
// the body but always leaves a banner (an HTML comment, stripped before
// injection by profileText()) noting it's auto-generated and embedding a
// fingerprint of the vault state it was built from, so a later call can
// tell whether the vault has drifted enough to warrant regenerating again.
// A manual edit survives until the next regeneration; regeneration only
// runs when profileStale() is true AND the caller has a configured LLM
// path (persona.js/PersonaChat decide that, not this module).

import { vault } from './store.js'
import { plainText, buildGraph } from './links.js'

export const PROFILE_TITLE = 'Persona Profile'
export const TOP_NOTE_COUNT = 8
/** Fraction of the top-note set (by id+updatedAt) that must change before the profile counts as stale. */
export const DRIFT_THRESHOLD = 0.2

const FINGERPRINT_RE = /<!--\s*fingerprint:\s*([^>]*?)\s*-->/

function isProfileTitle(title = '') {
  return title.trim().toLowerCase() === PROFILE_TITLE.toLowerCase()
}

function findProfileNote(state) {
  return state.notes.find((n) => isProfileTitle(n.title)) || null
}

/** The vault's strongest notes by synaptic strength (edits + degree*2), excluding the profile note itself. */
export function topNotes(state, n = TOP_NOTE_COUNT) {
  const { nodes } = buildGraph(state.notes)
  const strength = new Map(nodes.map((x) => [x.id, x.edits + x.degree * 2]))
  return [...state.notes]
    .filter((note) => !isProfileTitle(note.title))
    .sort((a, b) => (strength.get(b.id) || 0) - (strength.get(a.id) || 0))
    .slice(0, n)
}

/** A stable fingerprint of the current top-note set: sorted "id@updatedAt" pairs. Changes whenever membership OR any member's updatedAt changes. */
export function vaultFingerprint(state, n = TOP_NOTE_COUNT) {
  return topNotes(state, n)
    .map((note) => `${note.id}@${note.updatedAt}`)
    .sort()
    .join('|')
}

function fingerprintDrift(oldFingerprint, newFingerprint) {
  const oldEntries = oldFingerprint.split('|').filter(Boolean)
  if (!oldEntries.length) return 1
  const newEntries = new Set(newFingerprint.split('|').filter(Boolean))
  const changed = oldEntries.filter((e) => !newEntries.has(e)).length
  return changed / oldEntries.length
}

/** True when no profile exists yet, or the top-note set has drifted by more than DRIFT_THRESHOLD since the profile was last regenerated. */
export function profileStale(state) {
  const note = findProfileNote(state)
  if (!note) return true
  const match = note.body.match(FINGERPRINT_RE)
  if (!match) return true
  return fingerprintDrift(match[1], vaultFingerprint(state)) > DRIFT_THRESHOLD
}

/** The profile's prose, with the auto-generation banner/fingerprint comments stripped — what gets injected into the system prompt. '' if no profile note exists. */
export function profileText(state) {
  const note = findProfileNote(state)
  if (!note) return ''
  return note.body.replace(/<!--[\s\S]*?-->/g, '').trim()
}

/**
 * Regenerate the Persona Profile note from the vault's strongest notes via
 * ONE LLM call. `llmCall` is an injected `({ system, messages, maxTokens }) =>
 * Promise<string>` (usually llm.chat bound to the persona's configured
 * route) — this module never imports llm.js directly, so it stays trivially
 * testable with a fake and carries no opinion about routing/keys/auth.
 */
export async function regenerateProfile(state, llmCall) {
  const notes = topNotes(state)
  const corpus = notes
    .map((n) => `=== ${n.title} ===\n${plainText(n.body)}`)
    .join('\n\n')
    .slice(0, 12000)

  const content = await llmCall({
    system: [
      'You are distilling a personal knowledge vault into a concise "who I am" profile for a',
      "mind clone: the owner's values, voice/tone, decision heuristics, and areas of expertise.",
      'Write in first person, as the vault\'s owner would describe themselves. 200-400 words,',
      'short paragraphs, no headers needed. Ground every claim in the notes given below; never',
      'invent facts the notes do not support.',
    ].join(' '),
    messages: [
      {
        role: 'user',
        content: `Notes (strongest signal first):\n\n${corpus || '(the vault is still thin — write a brief, honest placeholder profile saying so, rather than inventing detail)'}`,
      },
    ],
    maxTokens: 700,
  })

  const fingerprint = vaultFingerprint(state)
  const banner =
    `<!-- auto-generated by Manyam Mind — Persona Profile. Regenerated from your strongest notes; ` +
    `manual edits may be overwritten the next time this regenerates. -->\n` +
    `<!-- fingerprint: ${fingerprint} -->\n\n`
  const body = banner + content.trim()

  const existing = findProfileNote(state)
  if (existing) {
    vault.updateNote(existing.id, { body })
    return { ...existing, body }
  }
  const note = vault.createNote(PROFILE_TITLE)
  vault.updateNote(note.id, { body })
  return { ...note, body }
}
