-- Superseded — Phase 1 (PLAN.md §1.2) moved this repo to ordered migrations.
--
-- The marketplace schema that used to live in this file is now
-- supabase/migrations/0001_marketplace.sql, and the sync-engine schema
-- (vault_docs + RLS) added in Phase 1 is supabase/migrations/0002_sync.sql.
-- Apply migrations in order via the Supabase CLI (`supabase db push`) or the
-- SQL editor, in ascending filename order.
